export const PreferenceConstant = {
    APP_LOGO: "APP_LOGO",
    SEARCH_PLACEHOLDER_TEXT: "SEARCH_PLACEHOLDER_TEXT",
    INSTAGRAM_URL: "INSTAGRAM_URL",
    FACEBOOK_URL: "FACEBOOK_URL",
    TWITTER_URL: "TWITTER_URL",
    PINTEREST_URL: "PINTEREST_URL",
    FOOTER_COPYRIGHT_TEXT: "FOOTER_COPYRIGHT_TEXT",
    POPULAR_CATEGORIES: "POPULAR_CATEGORIES",
    IS_SALE_LIVE: "IS_SALE_LIVE",
    IS_NEW_ARRIVALS: "IS_NEW_ARRIVALS",
    PAYMENT_LOGOS: "PAYMENT_LOGOS",
};
